name: workflow

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set Version
        run: |
          echo ::set-env name=RELEASE_VERSION::${GITHUB_REF:10}
      - name: Set Image Name
        run: echo ::set-env name=IMAGE_NAME::docker.pkg.github.com/${{ github.repository }}/${{ github.event.repository.name }}:${{ env.RELEASE_VERSION }}

      - name: Build The Docker Image
        run: |
          docker build . \
                  --build-arg TAG=${{ env.RELEASE_VERSION}} \
                  --file Dockerfile --tag  ${{ env.IMAGE_NAME }}
      - name: Push Image To Github Package
        run: |
          docker login docker.pkg.github.com -u ${{ github.actor }} -p ${{ secrets.GITHUB_TOKEN }}
          docker push ${{ env.IMAGE_NAME}}